version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=core
    ports:
      - '5433:5432'